### ISSUE TITLE
Moving for 2.40 to 2.41 or more crash

### ISSUE THREAD

**Issue by ScreamZ** [supabase/supabase-js#1016]
When bumping from 2.40 to 2.41 or later i get the following error using vue-cli with quasar framework.

```log
practitioner-frontend:dev: ✘ [ERROR] No matching export in "../../node_modules/@supabase/functions-js/dist/module/index.js" for import "FunctionRegion"
practitioner-frontend:dev:
practitioner-frontend:dev:     node_modules/@supabase/supabase-js/dist/module/index.js:3:87:
practitioner-frontend:dev:       3 │ export { FunctionsHttpError, FunctionsFetchError, FunctionsRelayError, FunctionsError, FunctionRegion, } from '@supabase/functions-js';
practitioner-frontend:dev:         ╵                                                                                        ~~~~~~~~~~~~~~
practitioner-frontend:dev:
practitioner-frontend:dev: 5:09:44 PM [vite] error while updating dependencies:
practitioner-frontend:dev: Error: Build failed with 1 error:
practitioner-frontend:dev: node_modules/@supabase/supabase-js/dist/module/index.js:3:87: ERROR: No matching export in "../../node_modules/@supabase/functions-js/dist/module/index.js" for import "FunctionRegion"
practitioner-frontend:dev:     at failureErrorWithLog (/Users/screamz/dev-workspace/pro/qanopee/qanopee-dev/node_modules/.pnpm/esbuild@0.14.51/node_modules/esbuild/lib/main.js:1621:15)
practitioner-frontend:dev:     at /Users/screamz/dev-workspace/pro/qanopee/qanopee-dev/node_modules/.pnpm/esbuild@0.14.51/node_modules/esbuild/lib/main.js:1263:28
practitioner-frontend:dev:     at runOnEndCallbacks (/Users/screamz/dev-workspace/pro/qanopee/qanopee-dev/node_modules/.pnpm/esbuild@0.14.51/node_modules/esbuild/lib/main.js:1043:63)
practitioner-frontend:dev:     at buildResponseToResult (/Users/screamz/dev-workspace/pro/qanopee/qanopee-dev/node_modules/.pnpm/esbuild@0.14.51/node_modules/esbuild/lib/main.js:1261:7)
practitioner-frontend:dev:     at /Users/screamz/dev-workspace/pro/qanopee/qanopee-dev/node_modules/.pnpm/esbuild@0.14.51/node_modules/esbuild/lib/main.js:1374:14
practitioner-frontend:dev:     at /Users/screamz/dev-workspace/pro/qanopee/qanopee-dev/node_modules/.pnpm/esbuild@0.14.51/node_modules/esbuild/lib/main.js:675:9
practitioner-frontend:dev:     at handleIncomingPacket (/Users/screamz/dev-workspace/pro/qanopee/qanopee-dev/node_modules/.pnpm/esbuild@0.14.51/node_modules/esbuild/lib/main.js:772:9)
practitioner-frontend:dev:     at Socket.readFromStdout (/Users/screamz/dev-workspace/pro/qanopee/qanopee-dev/node_modules/.pnpm/esbuild@0.14.51/node_modules/esbuild/lib/main.js:641:7)
practitioner-frontend:dev:     at Socket.emit (node:events:518:28)
practitioner-frontend:dev:     at addChunk (node:internal/streams/readable:559:12)
practitioner-frontend:dev: Vite Error, /node_modules/.q-cache/vite/spa/deps/@supabase_supabase-js.js?v=29a253c4 optimized info should be defined
practitioner-frontend:dev: Vite Error, /node_modules/.q-cache/vite/spa/deps/zod.js?v=8c0d7009 optimized info should be defined
practitioner-frontend:dev: Vite Error, /node_modules/.q-cache/vite/spa/deps/vee-validate.js?v=2dcccd21 optimized info should be defined
practitioner-frontend:dev: Vite Error, /node_modules/.q-cache/vite/spa/deps/vee-validate.js?v=2dcccd21 optimized info should be defined
practitioner-frontend:dev: Vite Error, /node_modules/.q-cache/vite/spa/deps/vee-validate.js?v=2dcccd21 optimized info should be defined
practitioner-frontend:dev: Vite Error, /node_modules/.q-cache/vite/spa/deps/vee-validate.js?v=2dcccd21 optimized info should be defined
practitioner-frontend:dev: Vite Error, /node_modules/.q-cache/vite/spa/deps/lodash-es.js?v=7c9efdbc optimized info should be defined
practitioner-frontend:dev: Vite Error, /node_modules/.q-cache/vite/spa/deps/@vee-validate_zod.js?v=203fe8e6 optimized info should be defined
practitioner-frontend:dev: Vite Error, /node_modules/.q-cache/vite/spa/deps/@vee-validate_zod.js?v=203fe8e6 optimized info should be defined
practitioner-frontend:dev: Vite Error, /node_modules/.q-cache/vite/spa/deps/zod.js?v=8c0d7009 optimized info should be defined
practitioner-frontend:dev: Vite Error, /node_modules/.q-cache/vite/spa/deps/zod.js?v=8c0d7009 optimized info should be defined
practitioner-frontend:dev: Vite Error, /node_modules/.q-cache/vite/spa/deps/vue-i18n.js?v=bbc858a4 optimized info should be defined
practitioner-frontend:dev: Vite Error, /node_modules/.q-cache/vite/spa/deps/lodash-es.js?v=d8ed2722 optimized info should be defined
practitioner-frontend:dev: Vite Error, /node_modules/.q-cache/vite/spa/deps/@supabase_supabase-js.js?v=e6997187 optimized info should be defined
practitioner-frontend:dev: Vite Error, /node_modules/.q-cache/vite/spa/deps/zod.js?v=8f40aa32 optimized info should be defined
practitioner-frontend:dev: Vite Error, /node_modules/.q-cache/vite/spa/deps/vee-validate.js?v=1acfdb44 optimized info should be defined
practitioner-frontend:dev: Vite Error, /node_modules/.q-cache/vite/spa/deps/@vee-validate_zod.js?v=36f86f45 optimized info should be defined
practitioner-frontend:dev: Vite Error, /node_modules/.q-cache/vite/spa/deps/zod.js?v=8f40aa32 optimized info should be defined
practitioner-frontend:dev: Vite Error, /node_modules/.q-cache/vite/spa/deps/vue-i18n.js?v=9d252db0 optimized info should be defined
practitioner-frontend:dev: Vite Error, /node_modules/.q-cache/vite/spa/deps/vee-validate.js?v=1acfdb44 optimized info should be defined
practitioner-frontend:dev: Vite Error, /node_modules/.q-cache/vite/spa/deps/@vee-validate_zod.js?v=36f86f45 optimized info should be defined
practitioner-frontend:dev: Vite Error, /node_modules/.q-cache/vite/spa/deps/zod.js?v=8f40aa32 optimized info should be defined
practitioner-frontend:dev: Vite Error, /node_modules/.q-cache/vite/spa/deps/vee-validate.js?v=1acfdb44 optimized info should be defined
practitioner-frontend:dev: Vite Error, /node_modules/.q-cache/vite/spa/deps/vee-validate.js?v=1acfdb44 optimized info should be defined
practitioner-frontend:dev: ✘ [ERROR] No matching export in "../../node_modules/@supabase/functions-js/dist/module/index.js" for import "FunctionRegion"
practitioner-frontend:dev:
practitioner-frontend:dev:     node_modules/@supabase/supabase-js/dist/module/index.js:3:87:
practitioner-frontend:dev:       3 │ export { FunctionsHttpError, FunctionsFetchError, FunctionsRelayError, FunctionsError, FunctionRegion, } from '@supabase/functions-js';
practitioner-frontend:dev:         ╵                                                                                        ~~~~~~~~~~~~~~
practitioner-frontend:dev:
practitioner-frontend:dev: 5:09:46 PM [vite] error while updating dependencies:
practitioner-frontend:dev: Error: Build failed with 1 error:
practitioner-frontend:dev: node_modules/@supabase/supabase-js/dist/module/index.js:3:87: ERROR: No matching export in "../../node_modules/@supabase/functions-js/dist/module/index.js" for import "FunctionRegion"
practitioner-frontend:dev:     at failureErrorWithLog (/Users/screamz/dev-workspace/pro/qanopee/qanopee-dev/node_modules/.pnpm/esbuild@0.14.51/node_modules/esbuild/lib/main.js:1621:15)
practitioner-frontend:dev:     at /Users/screamz/dev-workspace/pro/qanopee/qanopee-dev/node_modules/.pnpm/esbuild@0.14.51/node_modules/esbuild/lib/main.js:1263:28
practitioner-frontend:dev:     at runOnEndCallbacks (/Users/screamz/dev-workspace/pro/qanopee/qanopee-dev/node_modules/.pnpm/esbuild@0.14.51/node_modules/esbuild/lib/main.js:1043:63)
practitioner-frontend:dev:     at buildResponseToResult (/Users/screamz/dev-workspace/pro/qanopee/qanopee-dev/node_modules/.pnpm/esbuild@0.14.51/node_modules/esbuild/lib/main.js:1261:7)
practitioner-frontend:dev:     at /Users/screamz/dev-workspace/pro/qanopee/qanopee-dev/node_modules/.pnpm/esbuild@0.14.51/node_modules/esbuild/lib/main.js:1374:14
practitioner-frontend:dev:     at /Users/screamz/dev-workspace/pro/qanopee/qanopee-dev/node_modules/.pnpm/esbuild@0.14.51/node_modules/esbuild/lib/main.js:675:9
practitioner-frontend:dev:     at handleIncomingPacket (/Users/screamz/dev-workspace/pro/qanopee/qanopee-dev/node_modules/.pnpm/esbuild@0.14.51/node_modules/esbuild/lib/main.js:772:9)
practitioner-frontend:dev:     at Socket.readFromStdout (/Users/screamz/dev-workspace/pro/qanopee/qanopee-dev/node_modules/.pnpm/esbuild@0.14.51/node_modules/esbuild/lib/main.js:641:7)
practitioner-frontend:dev:     at Socket.emit (node:events:518:28)
practitioner-frontend:dev:     at addChunk (node:internal/streams/readable:559:12)
practitioner-frontend:dev: Vite Error, /node_modules/.q-cache/vite/spa/deps/@supabase_supabase-js.js?v=d8ed2722 optimized info should be defined
practitioner-frontend:dev: Vite Error, /node_modules/.q-cache/vite/spa/deps/lodash-es.js?v=56b782c8 optimized info should be defined
practitioner-frontend:dev: Vite Error, /node_modules/.q-cache/vite/spa/deps/zod.js?v=fe0c6331 optimized info should be defined
practitioner-frontend:dev: Vite Error, /node_modules/.q-cache/vite/spa/deps/vee-validate.js?v=0b5aa84a optimized info should be defined
practitioner-frontend:dev: Vite Error, /node_modules/.q-cache/vite/spa/deps/@vee-validate_zod.js?v=457a464e optimized info should be defined
practitioner-frontend:dev: Vite Error, /node_modules/.q-cache/vite/spa/deps/zod.js?v=fe0c6331 optimized info should be defined
practitioner-frontend:dev: Vite Error, /node_modules/.q-cache/vite/spa/deps/vee-validate.js?v=0b5aa84a optimized info should be defined
practitioner-frontend:dev: Vite Error, /node_modules/.q-cache/vite/spa/deps/@vee-validate_zod.js?v=457a464e optimized info should be defined
practitioner-frontend:dev: Vite Error, /node_modules/.q-cache/vite/spa/deps/zod.js?v=fe0c6331 optimized info should be defined
practitioner-frontend:dev: Vite Error, /node_modules/.q-cache/vite/spa/deps/vue-i18n.js?v=ef393be5 optimized info should be defined
practitioner-frontend:dev: Vite Error, /node_modules/.q-cache/vite/spa/deps/vee-validate.js?v=0b5aa84a optimized info should be defined
practitioner-frontend:dev: Vite Error, /node_modules/.q-cache/vite/spa/deps/vee-validate.js?v=0b5aa84a optimized info should be defined
practitioner-frontend:dev: ✘ [ERROR] No matching export in "../../node_modules/@supabase/functions-js/dist/module/index.js" for import "FunctionRegion"
practitioner-frontend:dev:
practitioner-frontend:dev:     node_modules/@supabase/supabase-js/dist/module/index.js:3:87:
practitioner-frontend:dev:       3 │ export { FunctionsHttpError, FunctionsFetchError, FunctionsRelayError, FunctionsError, FunctionRegion, } from '@supabase/functions-js';
practitioner-frontend:dev:         ╵                                                                                        ~~~~~~~~~~~~~~
practitioner-frontend:dev:
practitioner-frontend:dev: 5:09:47 PM [vite] error while updating dependencies:
practitioner-frontend:dev: Error: Build failed with 1 error:
practitioner-frontend:dev: node_modules/@supabase/supabase-js/dist/module/index.js:3:87: ERROR: No matching export in "../../node_modules/@supabase/functions-js/dist/module/index.js" for import "FunctionRegion"
practitioner-frontend:dev:     at failureErrorWithLog (/Users/screamz/dev-workspace/pro/qanopee/qanopee-dev/node_modules/.pnpm/esbuild@0.14.51/node_modules/esbuild/lib/main.js:1621:15)
practitioner-frontend:dev:     at /Users/screamz/dev-workspace/pro/qanopee/qanopee-dev/node_modules/.pnpm/esbuild@0.14.51/node_modules/esbuild/lib/main.js:1263:28
practitioner-frontend:dev:     at runOnEndCallbacks (/Users/screamz/dev-workspace/pro/qanopee/qanopee-dev/node_modules/.pnpm/esbuild@0.14.51/node_modules/esbuild/lib/main.js:1043:63)
practitioner-frontend:dev:     at buildResponseToResult (/Users/screamz/dev-workspace/pro/qanopee/qanopee-dev/node_modules/.pnpm/esbuild@0.14.51/node_modules/esbuild/lib/main.js:1261:7)
practitioner-frontend:dev:     at /Users/screamz/dev-workspace/pro/qanopee/qanopee-dev/node_modules/.pnpm/esbuild@0.14.51/node_modules/esbuild/lib/main.js:1374:14
practitioner-frontend:dev:     at /Users/screamz/dev-workspace/pro/qanopee/qanopee-dev/node_modules/.pnpm/esbuild@0.14.51/node_modules/esbuild/lib/main.js:675:9
practitioner-frontend:dev:     at handleIncomingPacket (/Users/screamz/dev-workspace/pro/qanopee/qanopee-dev/node_modules/.pnpm/esbuild@0.14.51/node_modules/esbuild/lib/main.js:772:9)
practitioner-frontend:dev:     at Socket.readFromStdout (/Users/screamz/dev-workspace/pro/qanopee/qanopee-dev/node_modules/.pnpm/esbuild@0.14.51/node_modules/esbuild/lib/main.js:641:7)
practitioner-frontend:dev:     at Socket.emit (node:events:518:28)
practitioner-frontend:dev:     at addChunk (node:internal/streams/readable:559:12)
```

## System information

- OS: [e.g. macOS, Windows] MacOS
- Version of supabase-js:  2.41
- Package manager : PNPM
- Working up to: 2.40

# Full deps

```json
"dependencies": {
    "@fullcalendar/core": "^6.1.11",
    "@fullcalendar/daygrid": "^6.1.11",
    "@fullcalendar/interaction": "^6.1.11",
    "@fullcalendar/luxon3": "^6.1.11",
    "@fullcalendar/timegrid": "^6.1.11",
    "@fullcalendar/vue3": "^6.1.11",
    "@googleapis/oauth2": "^1.0.5",
    "@qanopee/supabase-types": "workspace:^",
    "@quasar/extras": "^1.16.11",
    "@supabase/supabase-js": "^2.40.0",
    "@tanstack/vue-query": "^5.29.0",
    "@tanstack/vue-query-devtools": "^5.29.0",
    "@tato30/vue-pdf": "^1.9.6",
    "@vee-validate/zod": "^4.12.6",
    "@vueuse/components": "^10.9.0",
    "@vueuse/core": "^10.9.0",
    "apexcharts": "^3.48.0",
    "axios": "^1.6.7",
    "googleapis": "^134.0.0",
    "libphonenumber-js": "^1.10.59",
    "lodash-es": "^4.17.21",
    "luxon": "^3.4.4",
    "pinia": "^2.1.7",
    "qrcode.vue": "^3.4.1",
    "quasar": "^2.15.2",
    "vee-validate": "^4.12.6",
    "vue": "^3.4.18",
    "vue-advanced-cropper": "^2.8.8",
    "vue-i18n": "^9.11.1",
    "vue-router": "^4.0.12",
    "vue-tel-input": "^8.3.1",
    "vue-use-places-autocomplete": "^0.2.0",
    "vue3-apexcharts": "^1.5.2",
    "vue3-google-map": "^0.20.0",
    "zod": "^3.22.4"
  },
  "devDependencies": {
    "@intlify/vite-plugin-vue-i18n": "^7.0.0",
    "@intlify/vue-i18n-loader": "^4.2.0",
    "@qanopee/shared-front-utilities": "workspace:^",
    "@qanopee/tailwind-config": "workspace:^",
    "@quasar/app-vite": "^1.8.0",
    "@types/google.maps": "^3.55.7",
    "@types/lodash-es": "^4.17.12",
    "@types/luxon": "^3.4.2",
    "@types/node": "^20.12.7",
    "@types/vue-tel-input": "^2.1.6",
    "@typescript-eslint/eslint-plugin": "^5.10.0",
    "@typescript-eslint/parser": "^5.10.0",
    "autoprefixer": "^10.4.18",
    "eslint": "^8.11.0",
    "eslint-config-prettier": "^8.1.0",
    "eslint-plugin-vue": "^9.0.0",
    "postcss": "^8.4.35",
    "prettier": "^2.8.8",
    "prettier-plugin-tailwindcss": "^0.4.1",
    "tailwindcss": "^3.4.3",
    "typescript": "^5.4.2"
  },
```

**Comment by MiirzaBaig** [comment]
Could you assign me?
And explain .......

**Comment by ScreamZ** [comment]
> Could you assign me? And explain .......

I'm not allowed for that.

To explain, I'm using a project with supabase 2.40, that works well, but when doing `pnpm install supabase-js@2.41` or more, i get the following error in the vue CLI.
